// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCom1bTNGTk27YVzmXSJDy8paMZ_l2URok',
    appId: '1:150118273896:web:a4923ca6cf28c562533cdd',
    messagingSenderId: '150118273896',
    projectId: 'milkmint-dev',
    authDomain: 'milkmint-dev.firebaseapp.com',
    storageBucket: 'milkmint-dev.firebasestorage.app',
    measurementId: 'G-F7FTGVB5CN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Hhk-hOZyvRBYHVgnYjJMLhEO5Y8cEIw',
    appId: '1:150118273896:android:ae467b7f084d6c50533cdd',
    messagingSenderId: '150118273896',
    projectId: 'milkmint-dev',
    storageBucket: 'milkmint-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8cSojmF0NrVDzJXAUr7N_Vu9o92BSH7A',
    appId: '1:150118273896:ios:83a7e3ccd0f4f066533cdd',
    messagingSenderId: '150118273896',
    projectId: 'milkmint-dev',
    storageBucket: 'milkmint-dev.firebasestorage.app',
    iosBundleId: 'com.example.milkManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8cSojmF0NrVDzJXAUr7N_Vu9o92BSH7A',
    appId: '1:150118273896:ios:83a7e3ccd0f4f066533cdd',
    messagingSenderId: '150118273896',
    projectId: 'milkmint-dev',
    storageBucket: 'milkmint-dev.firebasestorage.app',
    iosBundleId: 'com.example.milkManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCom1bTNGTk27YVzmXSJDy8paMZ_l2URok',
    appId: '1:150118273896:web:b37fcd4d154ee1ea533cdd',
    messagingSenderId: '150118273896',
    projectId: 'milkmint-dev',
    authDomain: 'milkmint-dev.firebaseapp.com',
    storageBucket: 'milkmint-dev.firebasestorage.app',
    measurementId: 'G-XX3XBY9PHP',
  );

}