// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvU40QCI0Jj8SPAu2BIHRMWUt5Bzg5lA0',
    appId: '1:404484728694:web:c22a84e4eff51ab9567c57',
    messagingSenderId: '404484728694',
    projectId: 'smartdwaardev',
    authDomain: 'smartdwaardev.firebaseapp.com',
    storageBucket: 'smartdwaardev.firebasestorage.app',
    measurementId: 'G-JHFR6KG2GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGFKzuqEgUZbTOk-x5vnB3yPT92juJcGU',
    appId: '1:404484728694:android:4f3338d92ef8cb2e567c57',
    messagingSenderId: '404484728694',
    projectId: 'smartdwaardev',
    storageBucket: 'smartdwaardev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl1xgVWX1SaXoCwpOnjPYBU9SefJC3tnY',
    appId: '1:404484728694:ios:16ebdece022b255a567c57',
    messagingSenderId: '404484728694',
    projectId: 'smartdwaardev',
    storageBucket: 'smartdwaardev.firebasestorage.app',
    iosBundleId: 'com.example.milkManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl1xgVWX1SaXoCwpOnjPYBU9SefJC3tnY',
    appId: '1:404484728694:ios:16ebdece022b255a567c57',
    messagingSenderId: '404484728694',
    projectId: 'smartdwaardev',
    storageBucket: 'smartdwaardev.firebasestorage.app',
    iosBundleId: 'com.example.milkManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvU40QCI0Jj8SPAu2BIHRMWUt5Bzg5lA0',
    appId: '1:404484728694:web:b156a1b8c78cb3c3567c57',
    messagingSenderId: '404484728694',
    projectId: 'smartdwaardev',
    authDomain: 'smartdwaardev.firebaseapp.com',
    storageBucket: 'smartdwaardev.firebasestorage.app',
    measurementId: 'G-DL7X9CTDS7',
  );
}
